name: Android-CI

on: pull_request

jobs:

  KtLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: ktlint check
        run: ./gradlew ktlintCheck


  unit_tests:
    needs: [ Ktlint ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Unit tests
        run: ./gradlew test --stacktrace


  build_and_assemble:
    needs: [ unit_tests ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Assemble
        run: ./gradlew assembleDebug


