name: Android-CI

on: pull_request

jobs:

  KtLint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

      - name: ktlint check
        run: ./gradlew ktlintCheck


  unit_tests:
    needs: [ Ktlint ]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Unit tests
        run: ./gradlew test


  build_and_assemble:
    needs: [ unit_tests ]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Project
        run: ./gradlew build

      - name: Assemble
        run: ./gradlew assemble


